version: 0.0.{build}

image:
  - Visual Studio 2019
environment:
    matrix:
        - configuration: Debug
          platform: x64
        - configuration: Release
          platform: x64
max_jobs: 1
matrix:
  fast_finish: false
platform:
  - x64
branches:
  only:
    - master
    - dev
before_build:
  - cmd: |
      mkdir build;
      cmake -G "Visual Studio 16 2019" -A "%platform%" -S . -B build -DPCP_BUILD_TESTS=ON -DPCP_BUILD_BENCHMARKS=ON -DPCP_BUILD_EXAMPLES=OFF
build_script:
  - cmd: |
      cmake --build build --target pcp-tests --config "%configuration%"
      cmake --build build --target pcp-ds-benchmarks --config "%configuration%"
      cmake --build build --target pcp-algorithm-benchmarks --config "%configuration%"
test_script:
  - cmd: |
      cd build/test/"%configuration%"
      pcp-tests.exe
notifications:
  - provider: Email
    to:
      - tonthat.quocminh@gmail.com
    subject: 'Build {{status}}'
    on_build_status_changed: true

