version: 0.0.{build}

image:
  - Visual Studio 2019
  - Ubuntu2004
  - macos
configuration:
  - Debug
  - Release
max_jobs: 1
matrix:
  fast_finish: false
platform:
  - x64
branches:
  only:
    - master
    - dev
install:
  - sh: |
      sudo apt update
      sudo apt install g++-10
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
before_build:
  - sh: |
      mkdir build;
      cmake -S . -B build -DPCP_BUILD_TESTS=ON -DPCP_BUILD_BENCHMARKS=ON -DCMAKE_BUILD_TYPE=$(CONFIGURATION)
  - cmd: |
      mkdir build;
      cmake -A $(PLATFORM) -S . -B build -DPCP_BUILD_TESTS=ON -DPCP_BUILD_BENCHMARKS=ON
build_script:
  - sh: |
      cmake --build build --target pcp-tests;
      cmake --build build --target pcp-benchmarks
  - cmd: |
      cmake --build build --target pcp-tests --config $(CONFIGURATION);
      cmake --build build --target pcp-benchmarks --config $(CONFIGURATION)
test_script:
  - cmd: ./build/$(CONFIGURATION)/tests.exe
  - sh: ./build/tests
notifications:
  - provider: Email
    to:
      - tonthat.quocminh@gmail.com
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true
