version: 0.0.{build}

image:
  - Visual Studio 2019
  - Ubuntu2004
  - macos
environment:
    matrix:
        - configuration: Debug
          platform: x64
        - configuration: Release
          platform: x64
max_jobs: 1
matrix:
  fast_finish: false
platform:
  - x64
branches:
  only:
    - master
    - dev
install:
  - sh: |
      sudo apt update
      sudo apt --yes --force-yes install g++-10
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
before_build:
  - sh: |
      mkdir build;
      cmake -S . -B build -DPCP_BUILD_TESTS=ON -DPCP_BUILD_BENCHMARKS=ON -DCMAKE_BUILD_TYPE="%configuration%"
  - cmd: |
      mkdir build;
      cmake -G "Visual Studio 16 2019" -A "%platform%" -S . -B build -DPCP_BUILD_TESTS=ON -DPCP_BUILD_BENCHMARKS=ON
build_script:
  - sh: |
      cmake --build build --target pcp-tests
      cmake --build build --target pcp-benchmarks
  - cmd: |
      cmake --build build --target pcp-tests --config "%configuration%"
      cmake --build build --target pcp-benchmarks --config "%configuration%"
test_script:
  - cmd: ./build/"%configuration%"/tests.exe
  - sh: ./build/tests
notifications:
  - provider: Email
    to:
      - tonthat.quocminh@gmail.com
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true
