version: 0.0.{build}

image:
  - Ubuntu2004
environment:
    matrix:
        - configuration: Debug
          platform: x64
        - configuration: Release
          platform: x64
max_jobs: 1
matrix:
  fast_finish: false
platform:
  - x64
branches:
  only:
    - master
    - dev
before_build:
  - sh: |
      sudo apt install clang-10 lldb-10 lld-10 libc++-10-dev libc++abi-10-dev libomp-10-dev
      mkdir build;
      coverage=OFF
      if [ "$configuration" = "Debug" ]; then
        coverage=ON  
      fi
      export CC=/usr/bin/clang-10
      export CXX=/usr/bin/clang++-10
      cmake -S . -B build -DPCP_BUILD_TESTS=ON -DPCP_BUILD_BENCHMARKS=ON -DPCP_BUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=$configuration -DPCP_COVERAGE=$coverage
build_script:
  - sh: |
      cmake --build build --target pcp-tests
      cmake --build build --target pcp-benchmarks
test_script:
  - sh: ./build/test/pcp-tests
after_test:
  - sh: |
      bash <(curl -s https://codecov.io/bash)
notifications:
  - provider: Email
    to:
      - tonthat.quocminh@gmail.com
    subject: 'Build {{status}}'
    on_build_status_changed: true

